### ISSUE TITLE
eliminate global var in proc.example

### ISSUE THREAD

**Issue by fs-tom** [fsdonks/proc#9]
refactor (def marathons ....) into lexically-scoped var as discussed last week.

**Comment by mpavlak1** [comment]
Removed global atom. Added variable in do-multiple-charts to keep track of all the runs. Passed false to all formatting arguments and wait for all runs to be done to reformat charts so they only need to be formatted once instead of for each run. If there is a way to do multiple runs at once instead of sequentially, it would help speed it up. I tested do-multiple-charts from with the small and big data as the roots.
